name: Osama Ahmed
description: Blogging about stuffs
meta_description: "Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://oaattia.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Osama Ahmed'
